### ISSUE TITLE
regex problems

### ISSUE THREAD

**Issue by rehakm** [mprpic/advisory-parser#6]
There's a different output of the parser probably based on different versions of python used: python-3.7 vs python-3.6

**Comment by mprpic** [comment]
Bit more details: the actual issue is in the parsing of the latest Chrome release post. The security issues are sometimes not formatted as divs, which breaks splitting them by new lines. This was fixed in https://github.com/mprpic/advisory-parser/commit/a05cf939b0b9235f4b57c8d87135749374b2abc3 but not yet released, so folks running on the master-branch version would get the correct behavior.
